@echo off
echo Installing DBeaver...
winget install --id dbeaver.dbeaverce --silent --accept-package-agreements --accept-source-agreements

echo Installing Visual Studio Code...
winget install --id Microsoft.VisualStudioCode --silent --accept-package-agreements --accept-source-agreements

echo Installing WinSCP...
winget install --id WinSCP.WinSCP --silent --accept-package-agreements --accept-source-agreements

echo Installing MobaXterm...
winget install --id Mobatek.MobaXterm --silent --accept-package-agreements --accept-source-agreements

echo Installing Notepad++...
winget install --id Notepad++.Notepad++ --silent --accept-package-agreements --accept-source-agreements

echo Installing Steam...
winget install --id Valve.Steam --silent --accept-package-agreements --accept-source-agreements

echo Installing Battle.net...
winget install --id Blizzard.BattleNet --silent --accept-package-agreements --accept-source-agreements

echo Installing WhatsApp...
winget install --id 9NKSQGP7F2NH --silent --accept-package-agreements --accept-source-agreements

echo Installing Bitwarden...
winget install --id Bitwarden.Bitwarden --silent --accept-package-agreements --accept-source-agreements

echo Installing Kleopatra...
winget install --id Kleopatra.Kleopatra --silent --accept-package-agreements --accept-source-agreements

echo Installing Cyberduck...
winget install --id iterate.Cyberduck --silent --accept-package-agreements --accept-source-agreements

echo Installing Ubisoft Connect...
winget install --id Ubisoft.Uplay --silent --accept-package-agreements --accept-source-agreements

echo Installing EA app...
winget install --id ElectronicArts.EADesktop --silent --accept-package-agreements --accept-source-agreements

echo Installing Epic Games Launcher...
winget install --id EpicGames.EpicGamesLauncher --silent --accept-package-agreements --accept-source-agreements

echo Installing Google Chrome...
winget install --id Google.Chrome --silent --accept-package-agreements --accept-source-agreements

echo Installing Google Drive...
winget install --id Google.Drive --silent --accept-package-agreements --accept-source-agreements

echo Installing Discord...
winget install --id Discord.Discord --silent --accept-package-agreements --accept-source-agreements

echo Installing 7-Zip...
winget install --id 7zip.7zip --silent --accept-package-agreements --accept-source-agreements

echo Installing Transmission Remote GUI...
winget install --id Transmission.TransmissionRemoteGui --silent --accept-package-agreements --accept-source-agreements

echo Installing Bitdefender...
winget install --id Bitdefender.Bitdefender --silent --accept-package-agreements --accept-source-agreements

echo Installing HWMonitor...
winget install --id CPUID.HWMonitor --silent --accept-package-agreements --accept-source-agreements

echo All applications have been installed!
